### ISSUE TITLE
The example is using deprecated Magento\Framework\App\Action\Action;

### ISSUE THREAD

**Issue by florinm8** [AdobeDocs/commerce-learn.en#2]
The official documentation should point the correct way of doing things.

**Comment by ralbin** [comment]
Can you provide a link to the page you are referring to?  I am cleaning up the documentation pages to make sure they are correct.  I will continue to look for this example in the docs, but if you know what page you found this, it would expedite things.  Thank you for calling this out, we agree, our official documentation should show the correct way to accomplish a task.

**Comment by ralbin** [comment]
@florinm8 I have been unable to find the page that includes this deprecated method mentioned when you created this issue.  I think that tutorial must be removed by now because I just looked again and was unable to find it.  Please fill out another bug report if you spot another issue.  Sometimes our docs and tutorials can get a bit old and keeping them up to date is part of my responsibilities. However sometimes these code samples like the one you pointed out are harder to catch because we dont have PHPStorm to help us realized its deprecated.  Once again, thank you for helping with this, but it looks like that tutorial has been retired and no longer showing the wrong approach.
