### ISSUE TITLE
The video on this page stops at 2:25 and will not proceed.

### ISSUE THREAD

**Issue by bhouch12** [AdobeDocs/commerce-learn.en#3]
Issue in ./help/videos/merchant/static-dynamic-blocks.md

**Comment by ralbin** [comment]
This was resolved a while back, if you still have issues, please create a new issue

**Comment by ralbin** [comment]
@bhouch12 I just verified again this issue is resolved. We had a bug in the player when you submitted this issue.  Thankfully that is fixed and we are back to normal for a while now.  I really do appreciate you taking the time to fill out this bug report.  Please continue to use Experience League and let us know of any other issues you come across.
