### ISSUE TITLE
Documentation says "You are required to use the option attribute IDs not the labels"

### ISSUE THREAD

**Issue by brian-labelle** [AdobeDocs/commerce-learn.en#5]
Many Issues in ./help/site-management/catalog-import.md

- The documentation says that for CSV imports via API, "You are required to use the option attribute IDs not the labels"

  - However, this does not seem to be the case. Sending the attribute Option IDs actually seems to cause an error. It seems you actually have to send the labels now, not the values. Perhaps this has changed from when the document was last updated?

  - Also, https://experienceleague.adobe.com/en/docs/commerce-admin/systems/data-transfer/data-attributes-product does not indicate whether you need to use option IDs or labels

  - In `\Magento\CatalogImportExport\Model\Import\Product\Validator::validateOption`, it appears that it is checking a mapping of label => option id

- Under "Bulk REST API" tab:
  - "Time to import is important but not" -- the documentation just cuts off here -- the sentence isn't finished

- Under CSV Rest API Tab
  - "Data is needs to be in a CSV format" - this is listed as a con (and grammatically incorrect) -- why is this a con? It's the purpose of the CSV file import

**Comment by ralbin** [comment]
@brian-labelle Thanks for this feedback.  I just did a round of testing and it does appear this has changed.  I will be adjusting the documentation to remove that line.  Great catch!  I also fixed that incomplete sentence. Its been a long time since I wrote that article, I hope what I chose was what I meant to say way back then.  From what I recall there is a bit of a lag in processing the request if you compare it to the CSV style import.  I'll put it on my list to do some testing and see if I need to amend that statement to something else or just remove it and try to recall what I was trying to say.

**Comment by ralbin** [comment]
@brian-labelle  I hope you continue to use Experience League and if you do find any more bugs, please reach out like you did.  This is very helpful and I appreciate the time you took to fill out this issue.  I will be closing this now. The updates have been made and should be live today.
